pub mod autocleanup;
pub mod cleanup;
pub mod cli;
pub mod completion;
pub mod config;
pub mod daemon;
pub mod dispatch;
pub mod evidence;
pub mod ipc;
pub mod leak;
pub mod mcp;
pub mod memory_guard;
pub mod metrics;
pub mod monitor;
pub(crate) mod notification_session;
pub(crate) mod notifications;
pub mod packaging;
pub mod platform;
pub mod policy;
pub mod remediation;
pub mod resolution;
pub mod runtime;
pub mod safety;
pub mod setup;
mod setup_tui;
mod setup_ui;
